name: flutter_mon_loan_tracking
description: Loan Tracking application
version: 1.0.0+4
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: 3.22.1

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^5.2.1
  collection: ^1.18.0
  device_info_plus: ^10.1.2
  dotted_border: ^2.0.0+3
  drop_shadow: ^0.1.0
  equatable: ^2.0.5
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_form_builder: ^9.3.0
  form_builder_extra_fields: ^10.2.0
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.3
  form_builder_validators: ^11.0.0
  go_router: ^14.2.3
  http: ^1.2.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  jiffy: ^6.3.1
  json_annotation: ^4.8.0
  pdf: ^3.9.0
  printing: ^5.13.1
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  remove_alpha_ios: true
  image_path: "assets/icons/launcher_icon.png"
  image_path_ios: "assets/icons/launcher_icon2.png"
  min_sdk_android: 28
  web:
    generate: true
    image_path: "assets/icons/launcher_icon.png"
    background_color: "#FF815600"
    theme_color: "#FF815600"
