name: flutter_mon_loan_tracking
description: Loan Tracking application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.7.7

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.3.1
  collection: ^1.16.0
  dotted_border: ^2.0.0+3
  drop_shadow: ^0.1.0
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_form_builder: ^7.8.0
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.3
  form_builder_validators: ^8.5.0
  go_router: ^6.0.1
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.8.0
  pdf: ^3.9.0
  printing: ^5.10.1
  shared_preferences: ^2.0.18

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 28
  web:
    generate: true
    image_path: "assets/icons/launcher_icon.png"
    background_color: "#FF815600"
    theme_color: "#FF815600"
