// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2U3e4XLsuzk4v0oLQnA4D95VBhlPg_g',
    appId: '1:519992396424:web:7aee8afb27c089cf9bed3d',
    messagingSenderId: '519992396424',
    projectId: 'loan-tracking-system',
    authDomain: 'loan-tracking-system.firebaseapp.com',
    storageBucket: 'loan-tracking-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiDrl1PxAfc5u1UJ9D5x0g6sw0bY5OK7g',
    appId: '1:519992396424:android:04fea2aa420371c69bed3d',
    messagingSenderId: '519992396424',
    projectId: 'loan-tracking-system',
    storageBucket: 'loan-tracking-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4oxW2JnSjS1Tshxh2Hc-cv3djXGfeN9Y',
    appId: '1:519992396424:ios:a5deaf8dfb1b20b69bed3d',
    messagingSenderId: '519992396424',
    projectId: 'loan-tracking-system',
    storageBucket: 'loan-tracking-system.appspot.com',
    iosClientId: '519992396424-fmnf6pcun07hiabnta0e9jbp0nv2h9o3.apps.googleusercontent.com',
    iosBundleId: 'com.mon.loantracking.app',
  );
}
