// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5eiJ5olemOK3WCQIMSjOBuVP2uIVLUGg',
    appId: '1:516428407645:web:33eacc267e4e8130fcbeb4',
    messagingSenderId: '516428407645',
    projectId: 'loan-tracking-system-dev-stg',
    authDomain: 'loan-tracking-system-dev-stg.firebaseapp.com',
    storageBucket: 'loan-tracking-system-dev-stg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7KESzwfHY_uuR2gfd8eIi4QdH1d9Xb7A',
    appId: '1:516428407645:android:038827b417f26e5ffcbeb4',
    messagingSenderId: '516428407645',
    projectId: 'loan-tracking-system-dev-stg',
    storageBucket: 'loan-tracking-system-dev-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAQK_SSVk6EsIR8W2Xmvfd3vpH17ZE8D0',
    appId: '1:516428407645:ios:74383bc91e3934dafcbeb4',
    messagingSenderId: '516428407645',
    projectId: 'loan-tracking-system-dev-stg',
    storageBucket: 'loan-tracking-system-dev-stg.appspot.com',
    iosClientId: '516428407645-9ntoqe75nf3k71gq6qu40uiau7hmi929.apps.googleusercontent.com',
    iosBundleId: 'com.mon.loantracking.app.stg',
  );
}
